### ISSUE TITLE
When can we expect mdDataTable2 release ?

### ISSUE THREAD

**Issue by Ram569** [iamisti/mdDataTable2#1]
Hi,
     When can we expect the release of mdDataTable2 with filters and selection.

**Comment by iamisti** [comment]
Hi @Ram569 !
It's hard to tell, but I'm going to work on that on every weekend. It will have the basic functionalities in the first release, and then I will continuously add features to it.

Roughly I expect the first release to happen on the beginning of October.

**Comment by leolorenzoluis** [comment]
Any updates on the release?

**Comment by ganySA** [comment]
Yeah... any updates? This would be pretty cool.
